name: Script Workflow

on:
  workflow_dispatch:

jobs:
  script-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Script Workflow
        run: |
          echo "Hello, Script Workflow!"

      - name: Run Python Script
        run: python script.py
