name: First Workflow

on:
  schedule:
    - cron: '*/5 * * * *' # Runs in every 5 minutes

jobs:
  cron-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron Workflow
        run: |
          echo "Hello Cron Job!"
