name: Conditional Workflow

on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Build Backend Image
        uses: mokhlesurr031/gh-tutorial/.github/workflows/11-reusable-workflow.yml@main
