name: Value Pass Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Unnamed'

jobs:
  get-value-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Greetings Message
        run: |
          echo "message=Hello, ${{ github.event.inputs.name }}!" >> GITHUB_OUTPUT

        
  print-value-workflow-job:
    runs-on: ubuntu-latest
    needs: [get-value-workflow-job]

    steps:
      - name: Print Greetings Message
        run: |
          echo "${{ needs.get-value-workflow-job.outputs.message }}"